// ============================================================
//  FILE: server.js
//  ROLE: Application Entry Point (The "Main" file of the backend)
//  WHY THIS FILE EXISTS:
//    Every Node.js/Express app needs ONE main file that starts
//    everything. Think of this as the "front door" of your backend.
//    When you run `node server.js`, this is the file that runs first.
//  WHAT IT DOES:
//    1. Loads environment variables from .env
//    2. Creates the Express application
//    3. Connects to the MongoDB database
//    4. Registers all middleware (CORS, JSON parser)
//    5. Registers all API routes
//    6. Starts listening on a port for incoming requests
// ============================================================

// --- IMPORTS ---
const express = require("express");   // Express is the web framework (lets us create APIs)
const dotenv = require("dotenv");     // dotenv reads our .env file and loads the variables
const cors = require("cors");         // CORS allows our React frontend (different port) to talk to this server
const path = require("path");         // Core Node module for file paths
const connectDB = require("./config/db"); // Our custom DB connection function

// --- LOAD ENVIRONMENT VARIABLES ---
// This MUST be called before anything else so that process.env.XXX values are available
dotenv.config();

// --- CONNECT TO DATABASE ---
// This calls our db.js function to open the MongoDB connection
connectDB();

// --- CREATE THE EXPRESS APP ---
// express() creates a new web application instance
const app = express();

// =============================================================
//  MIDDLEWARE SECTION
//  Middleware = functions that run on EVERY request BEFORE
//  it reaches the route handler. Think of it as a checkpoint.
// =============================================================

// 1. CORS Middleware:
//    Without this, the browser blocks your React app from calling this API
//    because they run on different ports (5173 vs 5000).
app.use(cors());

// 2. JSON Body Parser:
//    This tells Express to automatically parse incoming request bodies
//    that are in JSON format. Without this, req.body would be undefined.
app.use(express.json());
//    This allows Express to parse data submitted from an HTML form (<form>)
app.use(express.urlencoded({ extended: true }));

// =============================================================
//  VIEW ENGINE & PUBLIC FOLDERS (EJS Setup)
// =============================================================

// Set the view engine to EJS
app.set("view engine", "ejs");
// Tell Express where the views folder is located
app.set("views", path.join(__dirname, "views"));

// Serve static files (CSS, Images, browser JS) from the 'public' folder
app.use(express.static(path.join(__dirname, "public")));

// =============================================================
//  ROUTES SECTION
//  Each "route" is a group of API endpoints.
//  We define them in separate files to keep code organized.
//  Format: app.use("/api/...", require("./routes/..."))
// =============================================================

// Auth routes: handles /api/auth/register and /api/auth/login
app.use("/api/auth", require("./routes/authRoutes"));

// Client routes: handles /api/clients (GET, POST, PUT, DELETE)
app.use("/api/clients", require("./routes/clientRoutes"));

// Project routes: handles /api/projects (GET, POST, PUT, DELETE)
app.use("/api/projects", require("./routes/projectRoutes"));

// Task routes: handles /api/tasks (GET, POST, PUT, DELETE)
app.use("/api/tasks", require("./routes/taskRoutes"));

// --- EJS VIEW ROUTES ---
// These routes just send the HTML pages to the browser
app.get("/", (req, res) => {
  res.render("index", { 
    title: "Welcome to Nexus EJS",
    message: "This HTML page was generated by the Express Server using EJS instead of React!" 
  });
});

app.get("/login", (req, res) => {
  res.render("login", { title: "Login" });
});

app.get("/register", (req, res) => {
  res.render("register", { title: "Register" });
});

app.get("/dashboard", (req, res) => {
  res.render("dashboard", { title: "Dashboard" });
});

app.get("/clients", (req, res) => {
  res.render("clients", { title: "Clients" });
});

app.get("/projects", (req, res) => {
  res.render("projects", { title: "Projects" });
});

app.get("/tasks", (req, res) => {
  res.render("tasks", { title: "Tasks" });
});

// =============================================================
//  START THE SERVER
//  process.env.PORT reads from .env (we set it to 5000)
//  The || 5000 is a fallback in case the .env value is missing
// =============================================================
const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
});
